
- name: Installing the Repo file
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed
    disable_gpg_check: true

- name: Enable the redis 6 version
  ansible.builtin.shell: yum module enable {{component}}:remi-6.2 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: /etc/{{component}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'  

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: /etc/{{component}}/{{component}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes 
